# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 401df02a84d7c06363009f6c1124224c516339b87322d82c1ed2b57f8cd96cbc25d2fed640dad3170ce34ebf610ce58a9b04411bfe9d109f9faeca21ac075e38

test:
  secret_key_base: 4e20429a3bcd98cb5bcf37cddff9845267bf3e0b5ac4b67ffe80bdc5f7e5c64ad9eb78bddb7b61a6612ef8000a912ec407adbaf82248bd259242c54897e0aa59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
